### ISSUE TITLE
Unable to find cloned playlist

### ISSUE THREAD

**Issue by aido28** [victor141516/spotify-liked-songs-bkp#6]
Good Evening,

I linked my Spotify to this service at approx 5:15PM AEST and am still unable to find the cloned playlist at 8:00PM AEST.

Is this service still active?

**Comment by aido28** [comment]
It’s been generated. Thank you for this service!

**Comment by victor141516** [comment]
@aido28 I forgot to write here yesterday. I was checking your account and there was a small bug I fixed, so now it should work as expected 👍 

If you find any new thing feel free to open a new issue.

Thanks!
